# Generated by Django 5.0.6 on 2024-06-01 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmanufacturemodel',
            options={'verbose_name': 'Product Manufacture', 'verbose_name_plural': 'Product Manufactures'},
        ),
    ]
